name: swim-pubsub
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - pip:
    - python-qpid_proton
    - git+https://git@github.com/eurocontrol-swim/rest-client.git
    - git+https://git@github.com/eurocontrol-swim/opensky-network-client.git
    - git+https://git@github.com/eurocontrol-swim/subscription-manager-client.git