
LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    swim-pubsub:
      level: DEBUG

    proton:
      level: INFO

BROKER:
  host: '0.0.0.0:5671'
  cert_db: '/media/alex/Data/dev/work/eurocontrol/deploy/secrets/rabbitmq/ca_certificate.pem'
  cert_file: '/media/alex/Data/dev/work/eurocontrol/deploy/secrets/rabbitmq/client/client_certificate.pem'
  cert_key: '/media/alex/Data/dev/work/eurocontrol/deploy/secrets/rabbitmq/client/client_key.pem'
  cert_password: 'swim-ti'

SUBSCRIPTION-MANAGER:
  host: 'localhost:8080'
  https: false
  timeout: 30
  verify: false